
@startuml
skinparam backgroundColor WhiteSmoke

title
  Unit test WITH test double
end title

skinparam rectangle {
    roundCorner 20
}

rectangle "Unit test" as UnitTest #DarkGrey

rectangle "Component\nunder test" as cut #MediumAquaMarine

rectangle "Test double" as TestDoubleDependency #DarkGrey {
  component "dependent method" as TestDoubleDependencyMethod #DarkGrey
}

UnitTest -> cut: test
cut -> TestDoubleDependencyMethod: using

legend left
|colors|
|<#MediumAquaMarine> production code in green |
|<#DarkGrey> test code in gray |
endlegend

@enduml