
@startuml
skinparam backgroundColor WhiteSmoke

title
  Unit test WITHOUT test double
end title

skinparam rectangle {
    roundCorner 20
}

rectangle "Unit test" as UnitTest #DarkGrey

rectangle "Component\nunder test" as cut #MediumAquaMarine

rectangle "Real dependency" as RealDependency #MediumAquaMarine {
  component "dependent method" as RealDependencyMut #MediumAquaMarine
}

UnitTest -> cut: test
cut -> RealDependencyMut: using

legend left
|colors|
|<#MediumAquaMarine> production code in green |
|<#DarkGrey> test code in gray |
endlegend

@enduml