
@startuml
skinparam backgroundColor WhiteSmoke

title
  Partial test double
end title

skinparam rectangle {
    roundCorner 20
}

rectangle "Unit test" as UnitTest #DarkGrey

rectangle "Component\nunder test" as cut #MediumAquaMarine

rectangle "Real dependency" as RealDependency #MediumAquaMarine {
  component "dependent method" as RealDependencyMut #DarkGrey
  component "other method" as RealDependencyOtherMethod #MediumAquaMarine
}

cut -> RealDependency: import
UnitTest --> cut: 1. import
UnitTest -> RealDependency: 2. import
UnitTest -> RealDependencyMut: 3. change

legend left
|colors|
|<#MediumAquaMarine> production code in green |
|<#DarkGrey> test code in gray |
endlegend

@enduml