
@startuml
skinparam backgroundColor White

title
  Full test double
end title

skinparam rectangle {
    roundCorner 20
}

rectangle "Unit test" as UnitTest #DarkGrey

rectangle "Interception\nlibrary proxy" as InterceptionLib #DarkGrey

rectangle "Component\nunder test" as cut #MediumAquaMarine

rectangle "Test double dependency" as TestDoubleDependency #DarkGrey {
  component "dependent method" as TestDoubleDependencyMethod #DarkGrey
}

rectangle "<strike>Real dependency" as RealDependency #MediumAquaMarine {
  component "<strike>other method" as RealDependencyOtherMethod #MediumAquaMarine
  component "<strike>dependent method" as RealDependencyMut #MediumAquaMarine
}

UnitTest -> InterceptionLib: use
InterceptionLib --> cut: to import
cut -> TestDoubleDependency: with\ntest double\nimport

legend left
|colors|
|<#MediumAquaMarine> production code in green |
|<#DarkGrey> test code in gray |
endlegend

@enduml