
@startuml
skinparam backgroundColor #EEEBDC

title
  Partial test double
end title

skinparam rectangle {
    roundCorner 20
}

rectangle "Unit test" as UnitTest #gray

rectangle "Component\nunder test" as cut #LightCoral

rectangle "Real dependency" as RealDependency #LightCoral {
  component "dependent method" as RealDependencyMut #gray
  component "other method" as RealDependencyOtherMethod #LightCoral
}

cut -> RealDependency: import
UnitTest --> cut: 1. import
UnitTest -> RealDependency: 2. import
UnitTest -> RealDependencyMut: 3. change

legend left
|colors|
|<#LightCoral> production code in pink |
|<#gray> test code in gray |
endlegend

@enduml