
@startuml
skinparam backgroundColor #EEEBDC

title
  Full test double
end title

skinparam rectangle {
    roundCorner 20
}

rectangle "Unit test" as UnitTest #gray

rectangle "Interception\nlibrary proxy" as InterceptionLib #gray

rectangle "Component\nunder test" as cut #LightCoral

rectangle "Test double dependency" as TestDoubleDependency #gray {
  component "dependent method" as TestDoubleDependencyMethod #gray
}

rectangle "<strike>Real dependency" as RealDependency #LightCoral {
  component "<strike>other method" as RealDependencyOtherMethod #LightCoral
  component "<strike>dependent method" as RealDependencyMut #LightCoral
}

UnitTest -> InterceptionLib: use
InterceptionLib --> cut: to import
cut -> TestDoubleDependency: with\ntest double\nimport

legend left
|colors|
|<#LightCoral> production code in pink |
|<#gray> test code in gray |
endlegend

@enduml