name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install jasmine globally
        run: npm i -g jasmine
      - name: Run jasmine-no-interception tests
        working-directory: ./jasmine-no-interception
        run: |
          npm install
          npm test
        env:
          CI: true
